### ISSUE TITLE
Translation source

### ISSUE THREAD

**Issue by Rughalt** [elfosardo/foundryvtt-dnd35e-lang-it-it#1]
To keep this as clean as possible, you can use http://www.editorifolli.it/gdr/d20system/ which has OGL translations for everything (so you can release it on foundry browser).

If you are on 35E Discord, please contact me! :)

**Comment by elfosardo** [comment]
@Rughalt hey! Thanks for the hint, nice to read you here :)
I'll check the link, I'm not on discord but I'll drop there some time.
BTW awesome job with your module!

**Comment by elfosardo** [comment]
going to close this as the translation source has been corrected
